highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://justdeserves.github.io/vitae
author: Chris Heath

baseurl: /Vitae/
title: Chris Heath's Resume
name: Chris Heath
email: justdeserves@hotmail.com
email_full: mailto:justdeserves@hotmail.com
website: github.io/vitae
website_full: https://justdeserves.github.io/vitae
github: justdeserves # username
twitter: chrisheath1979
tel: 07786 132251
tel_full: tel:+447786132251
google_maps: 'https://goo.gl/maps/Jk5PkPRUgp62'
address: Stalybridge
city: Manchester
country: United Kingdom
google_analytics: UA-72456098-1

# needed for travis-ci build
exclude: [vendor]
